AMB-08 Created Delivery Employee class
Adam-McButmil/soniak-bew-api pull request #12
Opened 2024-10-15 15:01 UTC by CharlotteMKainos

added models folder with delivery employee class within

2024-10-15 15:07 UTC, Aaron-Millen requested changes
Add Class Constructor

2024-10-16 08:30 UTC, lukemKainos requested changes

2024-10-16 08:30 UTC, lukemKainos commented on src/main/java/org/soniakbew/models/DeliveryEmployee.java
> +@SuppressWarnings("checkstyle:LineLength")
This can't be used

2024-10-16 08:30 UTC, lukemKainos commented on src/main/java/org/soniakbew/models/DeliveryEmployee.java
> +public class DeliveryEmployee {
Any reason why we didnt include a default constructor for this class?

2024-10-16 08:56 UTC, lukemKainos approved these changes

2024-10-16 08:58 UTC, Aaron-Millen approved these changes

2024-10-16 09:02 UTC, merged